config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'landings#index'

  resources :landings, :only => [:index]
  resources :dashboards do
    collection do
      get :search_user
      get :autocomplete_user_name
    end 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :picture, PictureUploader

  #METHODS
  def full_name
    "#{ first_name.try(:capitalize) } #{ last_name.try(:capitalize) }"
  end

  def full_address
    "#{address.capitalize}, #{city.capitalize}, #{state.capitalize}, #{zip_code}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(user)
    gflash :success => "User has been signed in successfully."
    dashboard_path(user.id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  autocomplete :user, :name, :extra_data => [:first_name, :last_name]

  before_action :get_user

  def update
    if @user.update_attributes(user_params)
      gflash :success => "User has been updated successfully."
      redirect_to dashboard_path(current_user.id)
    else
      render :edit
    end
  end

  def search_user

  end

  private

  def get_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :picture, :phone, :address, :city, :state, :zip_code, :dob)
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  layout 'landing'
  
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/dashboards/edit.html.erb
<div id="content">
  <div id="form" class="active-header"> <!-- remove .active-header class form this when u Activate Account -->
    <%= render :partial => '/shared/header' %>
    <div class="menubar">
      <div class="sidebar-toggler visible-xs">
        <i class="ion-navicon"></i>
      </div>

      <div class="page-title">
        Edit Your Profile
      </div>
    </div>

    <div class="content-wrapper">
      <%= form_for @user, url: dashboard_path(@user.id), method: "PUT", html: { class: "form-horizontal"} do |f| %>
        <div class="form-group">
          <label class="col-sm-2 col-md-2 control-label">First name</label>
          <div class="col-sm-10 col-md-8">
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 col-md-2 control-label">Last name</label>
          <div class="col-sm-10 col-md-8">
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 col-md-2 control-label">Display picture</label>
          <div>
            Upload Image
            <%= f.file_field :picture %>
          </div>
          <div id="imagePreview"></div>
        </div>        
        <div class="form-group">
          <label class="col-sm-2 col-md-2 control-label">Phone number</label>
          <div class="col-sm-10 col-md-8">
            <%= f.text_field :phone, class: "form-control" %>
          </div>
        </div>
        
        <div class="address">
          <div class="form-group">
            <label class="col-sm-2 col-md-2 control-label">Address</label>
            <div class="col-sm-10 col-md-8">
              <%= f.text_field :address, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-3 col-sm-offset-2">
              <%= f.text_field :city, class: "form-control", placeholder: "City" %>
            </div>
            <div class="col-sm-3">
              <%= f.text_field :state, class: "form-control", placeholder: "State" %>
            </div>
            <div class="col-sm-2 col-md-2">
              <%= f.text_field :zip_code, class: "form-control", placeholder: "Zip Code" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 col-md-2 control-label">Date of Birth </label>
          <div class="col-sm-10 col-md-8 col-lg-3">
            <div class="input-group " data-date-format="M dd, yyyy - HH:ii P" data-link-field="dtp_input1">
              <%= f.text_field :dob, class: "form-control", placeholder: "DOB" %>
              <span class="input-group-addon"><i class="fa fa-clock-o "></i></span>
            </div>
          </div>
        </div>
        <div class="form-group form-actions">
          <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Save', class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div><!--content-wrapper -->
  </div>
</div><!--#content -->

app/views/dashboards/search_user.html.erb
        <div id="content">
            <div id="users" class="members active-header"> <!-- remove .active-header class form this when u Activate Account -->
      
            <%= render :partial => '/shared/header' %>
      <div class="menubar fixed">
        <div class="sidebar-toggler visible-xs">
          <i class="ion-navicon"></i>
        </div>
        
        <div class="page-title client-title">
          INJURIES
        </div>
        <form class="search hidden-xs">
          <i class="fa fa-search"></i>
          <input type="text" name="q" placeholder="Search injuries...." />
          <%= autocomplete_field_tag :user_name, '',autocomplete_user_name_dashboards_path %>
          <input type="submit" />
        </form>
        <a href="injury-form.html" class="new-user btn btn-success pull-right">
          <span>Add Injury</span>
        </a>
      </div>

      <div class="content-wrapper">
        <div class="row page-controls">
         
        </div>

        
        <div class="row users-grid">
          
          

          
        </div>
      </div><!--content-wrapper -->
    </div>
    </div><!--#content -->

app/views/landings/index.html.erb
<header>
  <div class="header-content">
    <div class="header-content-inner">
        <h1>Your Favorite Source of Free Bootstrap Themes</h1>
        <hr>
        <p>Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!</p>
        <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
    </div>
  </div>
</header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">We've got what you need!</h2>
                    <hr class="light">
                    <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                    <a href="#" class="btn btn-default btn-xl">Get Started!</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">At Your Service</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
                        <h3>Sturdy Templates</h3>
                        <p class="text-muted">Our templates are updated regularly so they don't break.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>Ready to Ship</h3>
                        <p class="text-muted">You can use this theme as is, or you can make changes!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                        <h3>Up to Date</h3>
                        <p class="text-muted">We update dependencies to keep things fresh.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                        <h3>Made with Love</h3>
                        <p class="text-muted">You have to make your websites with love these days!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="https://unsplash.it/650/350?image=535" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="https://unsplash.it/650/350?image=534" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="https://unsplash.it/650/350?image=532" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="https://unsplash.it/650/350?image=533" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="https://unsplash.it/650/350?image=531" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="https://unsplash.it/650/350?image=625" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Free Download at Start Bootstrap!</h2>
                <a href="#" class="btn btn-default btn-xl wow tada">Download Now!</a>
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x wow bounceIn"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
                </div>
            </div>
        </div>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectingDhakad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
    <title>Connecting Dhakad</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag "dashboard", :media => "all" %>
    <%= javascript_include_tag "dashboard" %>
    
  </head>
  <body>
    <div id="wrapper">    
      <div id="sidebar-default" class="main-sidebar">
        <div class="current-user">
          <a href="index.html" class="home"><i class="fa fa-home"></i></a>
          <a href="help.html" class="help">Help</a>
          <a href="account-profile.html" class="name">Account <i class="fa fa-chevron-down"></i></a>
          <ul class="menu">
            <li><a href="account-profile.html">Account settings</a></li>
            <li><a href="account-billing.html">Billing</a></li>
            <li><a href="invite-users.html">Invite User</a></li>
            <li><a href="account-notifications.html">Notifications</a></li>
            <li><a href="account-support.html">Help / Support</a></li>
            <li><a href="<%= destroy_user_session_path %>">Sign out</a></li>
          </ul>
        </div>
        <div class="inner-sidebar">
          <div class="menu-section">
            <h3>General</h3>
            <ul>
              <li>
                <a href="company-dashboard.html">
                  <i class="ion-android-earth"></i> 
                  <span>Company Dashboard</span>
                </a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="clients.html">
                  <i class="ion-person-stalker"></i> 
                  <span>All Friends</span>
                </a>
              </li>          
            </ul>
            <ul>
              <li>
                <a href="index.html">
                  <i class="glyphicon glyphicon-dashboard"></i>
                  <span>Dashboard</span>
                </a>
              </li>
            </ul>
          </div>
          <div class="menu-section">
            <h3>Injury Management</h3>
            <ul>
              <li>
                <a href="account.html" class="toggled" data-toggle="sidebar" >
                  <i class="fa fa-ambulance"></i><span>Injuries</span>
                  <i class="fa fa-chevron-down"></i>
                </a>
                <ul class="submenu" style="display:block">
                  <li><a href="<%= search_user_dashboards_path %>">Search User</a></li>
                  <li><a href="injury-profile.html">Injury Profile</a></li>
                  <li><a href="#">All Transactions</a></li>
                  <li><a href="reports.html">Reports</a></li>
                  <li><a href="preferences.html">Preferences</a></li>
                </ul>
              </li>
              <li>
                <a href="account.html" data-toggle="sidebar">
                  <i class="fa fa-envelope"></i> <span>Mailbox</span>
                  <i class="fa fa-chevron-down"></i>
                </a>
                <ul class="submenu">
                  <li><a href="inbox-mail.html">Inbox</a></li>
                  <li><a href="email-templates.html">Email templates</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
        <!-- end inner-sidebar -->
        <div class="bottom-menu hidden-sm">
          <ul>
            <li><a href="account-support.html"><i class="ion-help"></i></a></li>
            <li>
              <a href="inbox-mail.html">
                <i class="ion-archive"></i>
                <span class="flag"></span>
              </a>
              <ul class="menu">
                <li><a href="#">5 unread messages</a></li>
                <li><a href="#">12 tasks completed</a></li>
              </ul>
            </li>
            <li><a href="signup.html"><i class="ion-log-out"></i></a></li>
          </ul>
        </div>
      </div><!--main-sidebar-->
      <%= yield %>
    </div><!--#wrapper -->
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>Creative - Start Bootstrap Theme</title>

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    
    <%= javascript_include_tag "landing" %>
    <%= stylesheet_link_tag "landing", :media => "all" %>
  </head>

  <body id="page-top">
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand page-scroll" href="#page-top">Start Bootstrap</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a class="page-scroll" href="#about">About</a>
            </li>
            <li>
              <a class="page-scroll" href="#services">Services</a>
            </li>
            <li>
              <a class="page-scroll" href="#portfolio">Portfolio</a>
            </li>
            <li>
              <a class="page-scroll" href="#contact">Contact</a>
            </li>            
            <% if current_user.blank? %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
            <% else %>
              <li><a href="<%= dashboard_path(current_user.id) %>">Dashboard</a></li>
              <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>

</html>

app/views/shared/_header.html.erb
<div class="activebar">
  <div class="active-inner clearfix">
    <h3><%= current_user.full_name %></h3>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>